const formActionTypes = {
  SET_A_SERVICE: 'SET_A_SERVICE',
  SET_MODE: 'SET_MODE',
  SET_FROM_LOCATION: 'SET_FROM_LOCATION',
  SET_TO_LOCATION: 'SET_TO_LOCATION',
  SET_READY_DATE: 'SET_READY_DATE',
  SET_INCOTERMS: 'SET_INCOTERMS',
  SET_TOTAL_CARGO: 'SET_TOTAL_CARGO',
  SET_TOTAL_VOLUME: 'SET_TOTAL_VOLUME',
  SET_TOTAL_WEIGHT: 'SET_TOTAL_WEIGHT',
  SET_WARNING: 'SET_WARNING',
  SET_EXPORT_FORWARDING: 'SET_EXPORT_FORWARDING',
  SET_IMPORT_CUSTOM_CLEARANCE: 'SET_IMPORT_CUSTOM_CLEARANCE',
  SET_CARGO_INSURANCE: 'SET_CARGO_INSURANCE',
  SET_TRANSPORT_DELIVERY: 'SET_TRANSPORT_DELIVERY',
  SET_SUBMIT: 'SET_SUBMIT'
}


export default formActionTypes;